/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StateRouteImport } from './routes/state'
import { Route as FundingFlowRouteImport } from './routes/funding-flow'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParishParishIdRouteImport } from './routes/parish.$parishId'
import { Route as ApiAssistantRouteImport } from './routes/api.assistant'

const StateRoute = StateRouteImport.update({
  id: '/state',
  path: '/state',
  getParentRoute: () => rootRouteImport,
} as any)
const FundingFlowRoute = FundingFlowRouteImport.update({
  id: '/funding-flow',
  path: '/funding-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParishParishIdRoute = ParishParishIdRouteImport.update({
  id: '/parish/$parishId',
  path: '/parish/$parishId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantRoute = ApiAssistantRouteImport.update({
  id: '/api/assistant',
  path: '/api/assistant',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/funding-flow': typeof FundingFlowRoute
  '/state': typeof StateRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/parish/$parishId': typeof ParishParishIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/funding-flow': typeof FundingFlowRoute
  '/state': typeof StateRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/parish/$parishId': typeof ParishParishIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/funding-flow': typeof FundingFlowRoute
  '/state': typeof StateRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/parish/$parishId': typeof ParishParishIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/funding-flow'
    | '/state'
    | '/api/assistant'
    | '/parish/$parishId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/funding-flow'
    | '/state'
    | '/api/assistant'
    | '/parish/$parishId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/funding-flow'
    | '/state'
    | '/api/assistant'
    | '/parish/$parishId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  FundingFlowRoute: typeof FundingFlowRoute
  StateRoute: typeof StateRoute
  ApiAssistantRoute: typeof ApiAssistantRoute
  ParishParishIdRoute: typeof ParishParishIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/state': {
      id: '/state'
      path: '/state'
      fullPath: '/state'
      preLoaderRoute: typeof StateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funding-flow': {
      id: '/funding-flow'
      path: '/funding-flow'
      fullPath: '/funding-flow'
      preLoaderRoute: typeof FundingFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parish/$parishId': {
      id: '/parish/$parishId'
      path: '/parish/$parishId'
      fullPath: '/parish/$parishId'
      preLoaderRoute: typeof ParishParishIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant': {
      id: '/api/assistant'
      path: '/api/assistant'
      fullPath: '/api/assistant'
      preLoaderRoute: typeof ApiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  FundingFlowRoute: FundingFlowRoute,
  StateRoute: StateRoute,
  ApiAssistantRoute: ApiAssistantRoute,
  ParishParishIdRoute: ParishParishIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
